
  - name: Ensure no existing process running
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    shell: |
      kill -9 $(cat /tmp/ansible_network_health_check_to/{{test_protocol}}_{{test_to_ip}}_{{test_port}}_PID)
      exit 0


  - name: ensure tmp folder doesnot exist for clean start
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    file:
      path: /tmp/ansible_network_health_check_to/
      state: absent

  - name: ensure folder exist
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    file:
      path: /tmp/ansible_network_health_check_to/
      state: directory

  - name: Copy Python to destination
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    copy:
      src: files/udpServer.py
      dest: /tmp/ansible_network_health_check_to/udpServer.py

  - name: Start Server
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    shell: |
      cd /tmp/ansible_network_health_check_to/
      python /tmp/ansible_network_health_check_to/udpServer.py {{test_to_ip}} {{test_port}} /tmp/ansible_network_health_check_to/{{test_protocol}}_{{test_to_ip}}_{{test_port}}_OUTPUT &
      PID=$!
      echo $PID > /tmp/ansible_network_health_check_to/{{test_protocol}}_{{test_to_ip}}_{{test_port}}_PID
      sleep 10
      if [ -f /proc/$PID/status ]
      then
         exit 0
      else
         exit -1
      fi
    async: 45
    poll: 0

  - name: register PID of udpServer.py
    delegate_to: "{{check_to_host}}"
    shell: "cat /tmp/ansible_network_health_check_to/{{test_protocol}}_{{test_to_ip}}_{{test_port}}_PID"
    register: PID_udpServer

#  - name: debug only
#    debug:
#      var: PID_udpServer

  - name: make sure file Exist
    delegate_to: "{{check_to_host}}"
#    when: check_to_host ==  inventory_hostname
    stat:
      path: "/proc/{{PID_udpServer.stdout}}/status"
    register: stat_result
    failed_when: not stat_result.stat.exists
